### ISSUE TITLE
Code style: форматирование

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#1]
В файле сбито форматирование (не везде правильные отступы, кое-где можно встретить }} ). Это считается очень дурным тоном. Посмотрите в Idea, она умеет сама форматировать код по пункту меню или горячим клавишам. Особенно тяжело читать if-ы

**Comment by escos** [comment]
Немного подправил отступы и форматирование.

**Comment by anastasiya-solodkaya** [comment]
Не везде стиль одинаковый. :) А почему вы не хотите отформатировать Идеей?
