### ISSUE TITLE
MyMultitable (code structure): сам алгоритм

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#10]
1. Вообще алгоритм правильный (и круто, что у вас можно аргументы вводить в любом порядке!
На самом деле у вас есть возможность найти в Math классе функции, которые найдут вам  минимум и максимум без проверок на "больше-меньше".

2. Не очень понятно, зачем переменные i и j объявлены значительно раньше использования, хотя запросто могут быть объявлены там же, где и использованы.

3. То же, что и (2), но про min-max, они явно не нужны в верхнем блоке, их объявление лучше опустить в другой блок, иначе может возникнуть недопонимание алгоритма (кажется, будто переменные объявлены именно там, где надо - но тогда где они используются?)

**Comment by escos** [comment]
1. Добавил из Math функцию определения минимума. 
2. Переменные определил непосредственно в циклах.
3. Переменные min,max объявлены теперь непосредственно перед использованием.

**Comment by anastasiya-solodkaya** [comment]
1. Такое ощущение, что стало еще сложнее. А почему нельзя использовать и min, и max вместо ветвления?
3. Только все же переменные у нас в одну строчку стараются не определять :)

**Comment by anastasiya-solodkaya** [comment]
И в методах checkingFirst, checkingArgs у нас объявления переменных зачем-то вперед инициализации

**Comment by escos** [comment]
1. Использовал функции min, max.
2. Определил обе переменные на разных строках)
