### ISSUE TITLE
Работа с командной строкой и в интерактивном режиме

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#13]
Я вот посмотрела сейчас и думаю, что кое-где пользователю может быть совершенно неочевидно, что вы такое от него хотите. Например
`java MyMultitable`
> Аргументы не введены!

В целом все, что вы здесь говорите - и так очевидно человеку, который набрал эту команду. Он правда не вводил этих аргументов. И, скорее всего, он по этому сообщению не сможет понять, что сделал не так. То же самое и для 1го аргумента. Есть смысл печатать небольшое описание в таком случае, что-то в духе "Укажите два целочисленных положительных аргумента m и n, программа напечатает для них таблицу умножения".

`java Sort` предлагает ввести функцию от 0 до 5, но для пользователя нет никакой информации, а что это за функция вообще? Что от него хотят. Мне вот надо код прочитать, чтобы это понять. Нужно какое-то разъяснение. :)

**Comment by escos** [comment]
Попытался максимально известить пользователя о всем происходящем, исправил мессаджи.

**Comment by anastasiya-solodkaya** [comment]
Good done!
