### ISSUE TITLE
Sort - bugs

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#14]
```
java Sort 
Выберите функцию (необходимо ввести число от 0 до 5)
0
Массив вещественных значений:

0.400.390.250.070.240.790.930.330.920.56
```

С выводом явно проблемы. :)

Подобные проблемы и в других алгоритмах Sort

+ нет перевода строки в конце, так что у меня еще и приглашение терминала с этим сливается.

Проверьте, пожалуйста, все алгоритмы, кое-где выводятся весьма неожиданные вещи при печати сгенерированного массива.

**Comment by escos** [comment]
Запустил у себя, все нормально(читабельно выводит)

**Comment by anastasiya-solodkaya** [comment]
Получается тогда, что беда с кроссплатформенностью. Я не очень понимаю, зачем вы там \b используете, кстати.

**Comment by escos** [comment]
Проверил еще раз все,выводит нормально. \b убрал, действительно не нужно это)

**Comment by anastasiya-solodkaya** [comment]
Если бага в кроссплатформенности, то у вас она не воспроизведется. Здесь скорее надо читать в документации, что из использованного вами может аукнуться пользователям другой системы. :)
