### ISSUE TITLE
Sort - переиспользование кода

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#15]
Генерация массива случайных чисел для int повторятся несколько раз, почему бы тогда ее не вынести в отдельный метод?

**Comment by escos** [comment]
Создал новый метод заполнения массива случайными числами.

**Comment by escos** [comment]
Да, кстати, в методе findNumber ведется поиск числа и количество таких чисел в массиве, 2 в 1 так сказать.
