### ISSUE TITLE
по сортировке

### ISSUE THREAD

**Issue by PaulVoit** [escos/java_1#17]
Рома, привет! А ты зачем все задачи в один класс засунул? Или так нужно? Или я что-то упустил по дз? Это  не ООП!)))

**Comment by escos** [comment]
Вечер добрый. Просто посчитал, что не стоит плодить программы и возможно реализовать все эти несложные задачи в одной. Думаю ничего страшного)

**Comment by anastasiya-solodkaya** [comment]
Было бы неплохо закрыть эту задачу :)
