### ISSUE TITLE
Sort: именование и UI

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#19]
1. massive переводится с английского как "огромный", наш массив - это array :)
2. Неплохо было бы получить исходный массив в строковом представлении до того, как мы его отсортировали или еще что-то сделали, но не в методе генерации его (потому что метод генерации просто генерирует, а там, где мы по сути весь UI делаем, то есть в main 
3. Лучше не печатать массив самому, а использовать уже существующий метод Arrays.toString/Arrays.deepToString

**Comment by escos** [comment]
1. Исправил на array.
2. Вынес в main вывод массива в строковом представлении с использованием Arrays.toString.
