### ISSUE TITLE
User experience: ввод коэффициентов квадратного уравнения

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#2]
Вы запрашиваете у пользователя сразу три коэффициента: a, b, c. И только после ввода всех трех коэффициентов определяете, что если a = 0, то ввод неверный. Вообще это недобро по отношению к пользователю - ошибки ввода стоит определять как можно раньше (то есть после каждого введенного числа). 

Вообще в задаче подразумевалось, что по a = 0 будет определено, что решать надо именно линейное уравнение. :smile:

**Comment by escos** [comment]
Теперь коэффициенты вводятся последовательно, а также при вводе а=0 решается линейное уравнение.

**Comment by anastasiya-solodkaya** [comment]
Тогда непонятно, зачем мы сначала пользователя просим выбрать, какое уравнение решить (1 или 2), если мы можем сами определить, что при a = 0 это линейное уравнение.

**Comment by escos** [comment]
Так я это изначально делал, чтобы совместить 2 задания.

**Comment by PaulVoit** [comment]
Здравствуйте, Анастасия! Почему у меня  idea выдает ошибку при попытке скомпиллировать? https://github.com/PaulVoit/Square

**Comment by anastasiya-solodkaya** [comment]
escos, а, теперь я поняла =)
ну в целом сейчас, наверно, можно оставить определение по первому коэффициенту, но все же это up to you, я думаю, что такой вариант тоже ок :+1:
