### ISSUE TITLE
Sort: random array

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#20]
Теперь этот массив случайных значений генерируется избыточно, например для "генерации случайных чисел от 0 до 1" он тоже генерируется, но зачем? Получается, что он создается не в той точке программы, где должен.

**Comment by escos** [comment]
Немного переделал программу, переставил методы, надеюсь это то, что вы имели в виду.

**Comment by anastasiya-solodkaya** [comment]
В общем и целом да, но теперь у нас используется то, что не стоит использовать - переменная, объявленная внутри case, видна везде ниже. Я бы предложила все же занести это сразу в методы, которые используют эту переменную. Это первый вариант. Второй вариант - делать что-то в духе
findMinimum(generationRandomArray());
А внутри уже в начале метода написать что-то в духе: "Поиск минимума в массиве " + Arrays.toString(array). 

Кстати, generationRandomArray лучше заменить на generateRandomArray(), ибо нужно описание действие, то есть глагол.

**Comment by escos** [comment]
Сделал по второму варианту.
