### ISSUE TITLE
Ветвления в MyMultitable.parseAndCheckArgument

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#22]
Вот этот вложенный код может быть трудновато читать. Попробуйте представить все это примерно как граф потока исполнения. Здесь можно обойтись всего 2мя return - одним для правильного значения и одним "-1" в самом конце метода. Если есть вопросы по этому поводу (почему так можно) - задавайте. =)

**Comment by escos** [comment]
Изменил, то есть избавился от лишнего ветвления
