### ISSUE TITLE
Code style: названия

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#3]
Названия методов (linear, square) не говорят ни о чем. По сути метод - это действие, надо подобрать именования, которые могли бы сразу сказать, что это. Например solveLinearEquation или что-то в таком духе.

То же самое - название класса Equal - вообще совпадает по сути с названием стандартного метода. Надо подобрать что-нибудь получше и помнемоничнее.

**Comment by escos** [comment]
Названия изменены.

**Comment by anastasiya-solodkaya** [comment]
Я думаю, нормально. :smile: 
Единственное стоить помнить - обычно методы называют глаголами. Например doSomething.
