### ISSUE TITLE
Code structure: Scanner

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#4]
Вы создаете сканнер три раза (и все - на одном System.in), это достаточно опасно (подумайте, почему). Лучше сделать его одного: 
- Либо передавать параметром метода 
- (Лучше) Либо статической переменной класса, которая видна во всех методах

**Comment by escos** [comment]
Создал статическую переменную класса, созданную на 1 system.in.
Вероятнее всего при вызове каждого метода, если в каждом создан сканер, будет затрачиваться большее количество ресурсов памяти,тем самым мы уменьшаем производительность.
Это наверное будет ощущаться в значительно больших программах.

**Comment by anastasiya-solodkaya** [comment]
Плюс несколько сканеров на одном и том же потоке (System.in) - явление неприятное, ведь мы модифицируем поток из нескольких мест одновременно
