### ISSUE TITLE
Code style: переменные

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#5]
1. sc_lin - это название не соответствует стандартным соглашениям java, необходимо придумать что-нибудь получше. 

2. объявлять несколько переменных в одну строку - можно, но **лучше не стоит**. Это вводит в заблуждение и приводит к трудностям чтения. 

3. Переменная x (в linear) объявлена  задолго до ее использования, это не есть хорошо

4. Вообще эта переменная x вам не нужна (судя по коду) - вы ее используете только для того, чтоюбы присвоить и тут же использовать. Она именно как переменная (место хранения) у вас не используется

5. Выводить на печать с аргументами типа "x = a/b" - плохой стиль (не сразу понятно, о чем это)

**Comment by escos** [comment]
1. Избавился от переменной sc_lin.
2. Объявил каждую переменную в отдельной строке.
3. Переменную х объявил перед ее использованием непосредственно и определил ее как отношение коэффициентов.
