### ISSUE TITLE
MyMultitable (code structure): вложенные конструкции

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#7]
Мне кажется, для проверки аргументов вложенные if'ы - лишние, там может быть конструкци if-elseif-else - она будет проще читаться. Кроме того, тогда уж неплохо, наверно, было бы для 3х аргументов писать что-то в духе "too much".

**Comment by escos** [comment]
Применил в методе main оператор switch, тем самым избавился от if-else. Также добавлена проверка на случай более 2х аргументов.

**Comment by anastasiya-solodkaya** [comment]
Good job! :+1:
