### ISSUE TITLE
MyMultitable - опять лишний пакет

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#8]
Для того, чтобы этого  не было, можно репозиторий делать прямо там, где проекты идеи лежат. Так как задачки маленькие, можно под них один проект создать, и честно хранить нужную иерархию папок. Только не забыть добавить в игнор *.iml и .idea

Можно даже пушить через идею

**Comment by escos** [comment]
Я отправлял файл с программой с рабочего компьютера, поэтому видимо разные респозитории. У меня до сих не получилось настроить push, поэтому приходится вручную программы закидывать на сервер. Пытался из командной строки настроить, ключ сгенерировал, вставил, а далее на одном месте выводит ошибку...пока не пойму что с делать.

**Comment by anastasiya-solodkaya** [comment]
Скиньте ошибку плиз, потому что вы за курс устанете так жить :)

**Comment by escos** [comment]
Скриншот скинул в чат
