### ISSUE TITLE
MyMultitable (user expirience) - ничего не понятно :)

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/java_1#9]
```
java MyMultitable 2
Аргумент первый = 2
Введите второй аргумент!

```

А зачем говорить, что первый аргумент - 2, если все равно нужно два аргумента? Не легче сразу написать, что программа требует два аргументв? :smile: 

```
java MyMultitable 2 3
Аргумент первый = 2
Аргумент второй = 3
       4       6

       6       9

Аргумент 2 введен не корректно, необходимо ввести значение больше нуля!
```

Это тоже не очень понятно. Вернее, вывод правильный, но откуда взялось второе сообщение?
Код с аргументами очень запутанный на самом деле, его так просто понять трудно. Предлагаю сначала обдумать user interface, а уже исходя из него делать вывод.

**Comment by escos** [comment]
Я хотел тем самым пользователя известить о том, что введен всего один аргумент,но введен онправильно.  Необходимо добавить всего еще один аргумент. Сообщение вылезло случайно, маленькая помарочка была). Код немного упростил, вроде стал понятнее.

**Comment by anastasiya-solodkaya** [comment]
1. Мне кажется, что лучше уж просто говорить, мол, введен один аргумент, а когда два - уже разбираться, правильно или нет. :) 

Если хотите оставить как есть, то checkingFirst название лучше заменить на более говорящее и разбить код так, чтобы было сразу понятно, что ничего в checjingFirst происходить не будет.

Сейчас checkingFirst и checkingArgs по названию как бы намекают, что действия у них почти одинаковые. Соответственно ожидания - либо checkingFirst умеет что-то считать и выводить, либо checkingArgs не умеет считать (тогда кто умеет?). Плюс герундий все-таки не лучший выбор формы глагола для названия метода. :)

Я предлагаю в таком случае немного подрихтовать структуру кода (как - решать вам). Самый простой способ - это перименовать методы согласно тому, что они делают на самом деле. Например checkingFirst на самом деле парсит и проверяет единственный аргумент. А checkingArgs парсит и проверяет два введенных аргумента, да потом еще и таблицу печатает.


2. Отдельной строкой сами мессаджи, случаи, когда у вас аргументы меньше 0 и когда там написано что-то неверное, на самом деле для пользователя никак не отличаются. Я думаю, что тут стоит ему разъяснить, что он ввел неправильно.

3. Огромное количество вложенных if-ов и try-ев за счет всех этих сообщений. Может быть, создать отдельную функцию, которая сумеет распарсить аргумент и проверить его корректность?

**Comment by escos** [comment]
1. Исправил мессаджи, уточнил в них что конкретно неправильно.
Также избавился от проверки одного аргумента.
2. Отдельную функцию, которая парсит и проверяет вводимые аргументы не получилось сделать, так как при определенном условии идет обращение к методу вывода таблицы. Есть вариант, как это сделать, разделив функцию проверки и вывода таблицы, но требуется ваша консультация. Если получится разделить. можно и вернуть проверку одного аргумента.
Название метода заменил на checkParseArgs.

**Comment by anastasiya-solodkaya** [comment]
А зачем вы отдельно сначала парсите аргументы, а потом проверяете, отрицательны ли они? Можно же проверку на отрицательность вставить туда же, где разбор аргумента. Тогда будет не parseArguments, а parseAndCheckArguments, и в целом все нормально. :)

**Comment by escos** [comment]
Объединил методы в parseAndCheckArguments
